# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 CreationWong
# See LICENSE for the license terms and warranty disclaimer.

version: 1
name: compose-app
type: docker-compose
file: docker-compose.yml
build: true
services:
  - web
env:
  APP_PORT: "8081"
