# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 CreationWong
# See LICENSE for the license terms and warranty disclaimer.

services:
  autodeploy:
    ports: !reset []
    networks:
      - default
      - gateway

networks:
  gateway:
    external: true
    name: ${AUTODEPLOY_NETWORK:-autodeploy-gateway}
