# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 CreationWong
# See LICENSE for the license terms and warranty disclaimer.

name: ci

on: [push]

env:
  PYTHONUNBUFFERED: "1"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 校验项目文件
        run: python3 .AutoDeploy/check.py files
      - name: 语法检查
        run: python3 .AutoDeploy/check.py syntax
      - name: 通过 GITHUB_ENV 传递变量
        run: python3 .AutoDeploy/check.py export-env
      - name: 读取上一步变量
        run: python3 .AutoDeploy/check.py print-env
